import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import type { ScheduleEvent } from "@/types/teamup";

const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    backgroundColor: "#ffffff",
    padding: 40,
  },
  header: {
    marginBottom: 28,
    borderBottomWidth: 2,
    borderBottomColor: "#0d0d0d",
    paddingBottom: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  gymName: {
    fontSize: 22,
    fontFamily: "Helvetica-Bold",
    color: "#0d0d0d",
  },
  subtitle: {
    fontSize: 10,
    color: "#888888",
    marginTop: 3,
  },
  date: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: "#0d0d0d",
    textAlign: "right",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#0d0d0d",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 3,
    marginBottom: 4,
  },
  tableHeaderText: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: "#ffffff",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  row: {
    flexDirection: "row",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  rowAlt: {
    backgroundColor: "#fafafa",
  },
  rowReserved: {
    backgroundColor: "#f5f5f5",
    opacity: 0.7,
  },
  colTime: {
    width: "22%",
  },
  colClass: {
    width: "48%",
  },
  colInstructor: {
    width: "30%",
  },
  cellText: {
    fontSize: 11,
    color: "#1a1a1a",
  },
  cellTextReserved: {
    fontSize: 11,
    color: "#aaaaaa",
    fontFamily: "Helvetica-Oblique",
  },
  cellTime: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: "#0d0d0d",
  },
  cellTimeReserved: {
    fontSize: 11,
    color: "#bbbbbb",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  footerText: {
    fontSize: 9,
    color: "#cccccc",
  },
  noEvents: {
    textAlign: "center",
    fontSize: 13,
    color: "#aaaaaa",
    marginTop: 40,
  },
});

function formatDisplayDate(dateStr: string): string {
  const [year, month, day] = dateStr.split("-").map(Number);
  const date = new Date(year, month - 1, day);
  return date.toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

interface SchedulePDFProps {
  events: ScheduleEvent[];
  date: string;
}

function SchedulePDF({ events, date }: SchedulePDFProps) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.gymName}>The Arena Lilburn</Text>
            <Text style={styles.subtitle}>Daily Schedule</Text>
          </View>
          <Text style={styles.date}>{formatDisplayDate(date)}</Text>
        </View>

        <View style={styles.tableHeader}>
          <Text style={[styles.tableHeaderText, styles.colTime]}>Time</Text>
          <Text style={[styles.tableHeaderText, styles.colClass]}>Class / Session</Text>
          <Text style={[styles.tableHeaderText, styles.colInstructor]}>Instructor</Text>
        </View>

        {events.length === 0 ? (
          <Text style={styles.noEvents}>No events scheduled for today.</Text>
        ) : (
          events.map((event, index) => {
            const isReserved = event.type === "reserved";
            const isAlt = index % 2 !== 0;

            return (
              <View
                key={event.id}
                style={[
                  styles.row,
                  isAlt && !isReserved ? styles.rowAlt : {},
                  isReserved ? styles.rowReserved : {},
                ]}
              >
                <View style={styles.colTime}>
                  <Text style={isReserved ? styles.cellTimeReserved : styles.cellTime}>
                    {event.time}
                  </Text>
                </View>
                <View style={styles.colClass}>
                  <Text style={isReserved ? styles.cellTextReserved : styles.cellText}>
                    {event.title}
                  </Text>
                </View>
                <View style={styles.colInstructor}>
                  <Text style={isReserved ? styles.cellTextReserved : styles.cellText}>
                    {event.instructor}
                  </Text>
                </View>
              </View>
            );
          })
        )}

        <View style={styles.footer}>
          <Text style={styles.footerText}>The Arena Lilburn</Text>
          <Text style={styles.footerText}>Generated by Apex Digital</Text>
        </View>
      </Page>
    </Document>
  );
}

export async function generateSchedulePDF(events: ScheduleEvent[], date: string): Promise<Buffer> {
  return renderToBuffer(<SchedulePDF events={events} date={date} />);
}
